/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system.Employee;

import hospital.management.system.Discharge.DischargeInfo;
import hospital.management.system.Discharge.DischargeRegistration;
import hospital.management.system.Doctor.DoctorInfo;
import hospital.management.system.Patient.InPatientRegistration;
import hospital.management.system.Patient.OutPatientRegistration;
import hospital.management.system.Patient.PatientInformation;
import hospital.management.system.Pharmacy.PharmacyInfo;
import hospital.management.system.Pharmacy.PharmacyRegistration;
import hospital.management.system.loginForm;
import hospital.management.system.userDetails;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Sumanta
 */
public class EmployeeMenu extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeMenu
     */
    public EmployeeMenu() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        
        lbl_userName.setText(userDetails.userName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_myInfo = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        lbl_userName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_doctorInfo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        combo_patient = new javax.swing.JComboBox<>();
        btn_patient = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        combo_pharmacy = new javax.swing.JComboBox<>();
        btn_pharmacy = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        combo_discharge = new javax.swing.JComboBox<>();
        btn_discharge = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        jPanel1.setLayout(null);

        btn_myInfo.setText("My Info");
        btn_myInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_myInfoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_myInfo);
        btn_myInfo.setBounds(320, 140, 130, 40);

        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel1.add(btn_logout);
        btn_logout.setBounds(630, 480, 94, 40);
        jPanel1.add(lbl_userName);
        lbl_userName.setBounds(170, 480, 78, 31);

        jLabel2.setText("Logged in as:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 480, 78, 31);

        btn_doctorInfo.setText("Doctor Info");
        btn_doctorInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doctorInfoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_doctorInfo);
        btn_doctorInfo.setBounds(320, 360, 130, 43);

        jLabel3.setText("Patient Corner");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(190, 190, 100, 40);

        combo_patient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "InPatient Registration", "OutPatient Registration", "Patient Info" }));
        jPanel1.add(combo_patient);
        combo_patient.setBounds(310, 190, 160, 40);

        btn_patient.setText("Get Patient Tab");
        btn_patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_patientActionPerformed(evt);
            }
        });
        jPanel1.add(btn_patient);
        btn_patient.setBounds(490, 183, 157, 50);

        jLabel4.setText("Pharmacy Corner");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(190, 250, 100, 40);

        combo_pharmacy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pharmacy Registration", "Pharmacy Info" }));
        jPanel1.add(combo_pharmacy);
        combo_pharmacy.setBounds(310, 250, 160, 40);

        btn_pharmacy.setText("Get Pharmacy Tab");
        btn_pharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pharmacyActionPerformed(evt);
            }
        });
        jPanel1.add(btn_pharmacy);
        btn_pharmacy.setBounds(490, 240, 157, 50);

        jLabel5.setText("Discharge Corner");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(190, 310, 100, 40);

        combo_discharge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Discharge Registration", "Discharge Info" }));
        jPanel1.add(combo_discharge);
        combo_discharge.setBounds(310, 310, 160, 40);

        btn_discharge.setText("Get Discharge Tab");
        btn_discharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dischargeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_discharge);
        btn_discharge.setBounds(490, 300, 157, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        
        loginForm lForm = new loginForm();
        lForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_patientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_patientActionPerformed
        // TODO add your handling code here:
        
        if (combo_patient.getSelectedItem().equals("InPatient Registration")) {
            InPatientRegistration ipReg = new InPatientRegistration();
            ipReg.setVisible(true);
        }
        else if (combo_patient.getSelectedItem().equals("OutPatient Registration")) {
            OutPatientRegistration opReg = new OutPatientRegistration();
            opReg.setVisible(true);
        }
        else if (combo_patient.getSelectedItem().equals("Patient Info")) {
            PatientInformation pInfo = new PatientInformation();
            pInfo.setVisible(true);
        }
    }//GEN-LAST:event_btn_patientActionPerformed

    private void btn_pharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pharmacyActionPerformed
        // TODO add your handling code here:
        
        if (combo_pharmacy.getSelectedItem().equals("Pharmacy Registration")) {
            PharmacyRegistration pReg = new PharmacyRegistration();
            pReg.setVisible(true);
        }
        else if (combo_pharmacy.getSelectedItem().equals("Pharmacy Info")) {
            PharmacyInfo pInfo = new PharmacyInfo();
            pInfo.setVisible(true);
        }
    }//GEN-LAST:event_btn_pharmacyActionPerformed

    private void btn_dischargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dischargeActionPerformed
        // TODO add your handling code here:
        
        if (combo_discharge.getSelectedItem().equals("Discharge Registration")) {
            DischargeRegistration dReg = new DischargeRegistration();
            dReg.setVisible(true);
        }
        else if (combo_discharge.getSelectedItem().equals("Discharge Info")) {
            DischargeInfo dInfo = new DischargeInfo();
            dInfo.setVisible(true);
        }
    }//GEN-LAST:event_btn_dischargeActionPerformed

    private void btn_doctorInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doctorInfoActionPerformed
        // TODO add your handling code here:
        
        DoctorInfo dInfo = new DoctorInfo();
        dInfo.setVisible(true);
    }//GEN-LAST:event_btn_doctorInfoActionPerformed

    private void btn_myInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_myInfoActionPerformed
        // TODO add your handling code here:
        
        EmployeeMyInfo eInfo = new EmployeeMyInfo();
        eInfo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_myInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_discharge;
    private javax.swing.JButton btn_doctorInfo;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_myInfo;
    private javax.swing.JButton btn_patient;
    private javax.swing.JButton btn_pharmacy;
    private javax.swing.JComboBox<String> combo_discharge;
    private javax.swing.JComboBox<String> combo_patient;
    private javax.swing.JComboBox<String> combo_pharmacy;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_userName;
    // End of variables declaration//GEN-END:variables
}
