/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system.Employee;

import hospital.management.system.Database;
import hospital.management.system.loginForm;
import hospital.management.system.userDetails;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Sumanta
 */
public class EmployeeMyInfo extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form EmployeeMyInfo
     */
    public EmployeeMyInfo() {
        initComponents();
        conn = Database.java_db();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        initiateFormValues();
    }

    private void initiateFormValues() {
        try {
            loginId = userDetails.loginId;
            
            String sql = "Select * from Employee where loginId = ? ";
            pst = conn.prepareStatement(sql);
            pst.setString(1, loginId);
            rs = pst.executeQuery();
            
            while (rs.next()) {
                String name = rs.getString("name");
                txt_name.setText(name);
                
                String logId = rs.getString("loginId");
                txt_loginId.setText(logId);
                
                String password = rs.getString("password");
                txt_password.setText(password);
                txt_confirmPassword.setText(password);
                
                String dept = rs.getString("department");
                txt_department.setText(dept);
               
                String conNo = rs.getString("contactNo");
                txt_contactNo.setText(conNo);
            }
        }
        catch (Exception e) {
            System.out.print(e);
        }
        finally {
            try {
                rs.close();
                pst.close();
            }
            catch (Exception e) {
                System.out.print(e);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_department = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_loginId = new javax.swing.JTextField();
        txt_contactNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_confirmPassword = new javax.swing.JPasswordField();
        txt_password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        jPanel1.setLayout(null);
        jPanel1.add(txt_department);
        txt_department.setBounds(387, 297, 203, 33);
        jPanel1.add(txt_name);
        txt_name.setBounds(387, 117, 203, 33);

        txt_loginId.setEditable(false);
        jPanel1.add(txt_loginId);
        txt_loginId.setBounds(387, 162, 203, 33);
        jPanel1.add(txt_contactNo);
        txt_contactNo.setBounds(387, 342, 203, 33);

        jLabel1.setText("Login Id");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(231, 162, 130, 33);

        jLabel2.setText("Confirm Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(231, 252, 130, 33);

        jLabel3.setText("Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(231, 207, 130, 33);

        jLabel4.setText("Contact No");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(231, 342, 130, 33);

        jLabel5.setText("Department");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(231, 297, 130, 33);

        jLabel6.setText("Name");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(231, 123, 130, 33);
        jPanel1.add(txt_confirmPassword);
        txt_confirmPassword.setBounds(387, 252, 203, 33);
        jPanel1.add(txt_password);
        txt_password.setBounds(387, 207, 203, 33);

        jButton1.setText("Confirm Change");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(410, 420, 130, 50);

        jButton2.setText("Clear Form");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(270, 420, 130, 50);

        jButton3.setText("Home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(120, 420, 130, 50);

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete);
        btn_delete.setBounds(560, 420, 130, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        EmployeeMenu eMenu = new EmployeeMenu();
        eMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        txt_confirmPassword.setText("");
        txt_contactNo.setText("");
        txt_department.setText("");
        txt_name.setText("");
        txt_password.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String name = txt_name.getText();
        String logId = txt_loginId.getText();
        String pword = txt_password.getText();
        String dept = txt_department.getText();
        String conNo = txt_contactNo.getText();
        
        int x = JOptionPane.showConfirmDialog(null, "Confirm update task ?", "Update Record", JOptionPane.YES_NO_OPTION);
        if (txt_password.getText().equals(txt_confirmPassword.getText())) {
            if (x == 0) {
                try {
                    String sql = "update Employee set name = ? ,loginId = ? ,password = ? ,department = ?" 
                            + " ,contactNo = ? where loginId = ?";
                    pst = conn.prepareStatement(sql);
                    pst.setString(1, name);
                    pst.setString(2, logId);
                    pst.setString(3, pword);
                    pst.setString(4, dept);
                    pst.setString(5, conNo);
                    pst.setString(6, loginId);
                    pst.execute();

                    JOptionPane.showMessageDialog(null, "Record Updated");
                }
                catch (Exception e) {
                    System.out.print(e);
                }
                finally {
                    try {
                        pst.close();
                    }
                    catch (Exception e) {
                        System.out.print(e);
                    }
                }
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Passwords do not match");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        
        int x = JOptionPane.showConfirmDialog(null, "Confirm deletion task ?", "Delete Record", JOptionPane.YES_NO_OPTION);
        if (x == 0) {
            try {
                String sql = "delete from Employee where loginId = ? ";

                pst = conn.prepareStatement(sql);
                pst.setString(1, txt_loginId.getText());
                pst.execute();

                JOptionPane.showMessageDialog(null, "Record deleted");
            }
            catch (Exception e) {

            }
            finally {
                try {
                    pst.close();

                    loginForm lform = new loginForm();
                    lform.setVisible(true);
                    this.dispose();
                }
                catch (Exception e) {

                }
            }
        }       
    }//GEN-LAST:event_btn_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeMyInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeMyInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeMyInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeMyInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeMyInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txt_confirmPassword;
    private javax.swing.JTextField txt_contactNo;
    private javax.swing.JTextField txt_department;
    private javax.swing.JTextField txt_loginId;
    private javax.swing.JTextField txt_name;
    private javax.swing.JPasswordField txt_password;
    // End of variables declaration//GEN-END:variables
    private String loginId;
}
