/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system.Patient;

import hospital.management.system.Database;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Sumanta
 */
public class OutPatientRegistration extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form OutPatientRegistration
     */
    public OutPatientRegistration() {
        initComponents();
        conn = Database.java_db();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_appointmentDate = new javax.swing.JTextField();
        txt_patientName = new javax.swing.JTextField();
        txt_patientId = new javax.swing.JTextField();
        txt_age = new javax.swing.JTextField();
        txt_contactNo = new javax.swing.JTextField();
        txt_department = new javax.swing.JTextField();
        txt_doctor = new javax.swing.JTextField();
        combo_gender = new javax.swing.JComboBox<>();
        button_register = new javax.swing.JButton();
        button_clearForm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        jPanel1.setLayout(null);

        jLabel1.setText("Appointment Date");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(440, 340, 110, 40);

        jLabel2.setText("Patient Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 160, 110, 40);

        jLabel3.setText("Patient Id");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 220, 110, 40);

        jLabel4.setText("Gender");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 280, 110, 40);

        jLabel5.setText("Age");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 340, 110, 40);

        jLabel6.setText("Contact No");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(440, 160, 110, 40);

        jLabel7.setText("Department");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(440, 210, 110, 40);

        jLabel8.setText("Doctor");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(440, 280, 110, 40);

        txt_appointmentDate.setText("dd:mm:yyyy");
        jPanel1.add(txt_appointmentDate);
        txt_appointmentDate.setBounds(560, 340, 170, 40);
        jPanel1.add(txt_patientName);
        txt_patientName.setBounds(180, 160, 170, 40);
        jPanel1.add(txt_patientId);
        txt_patientId.setBounds(180, 220, 170, 40);
        jPanel1.add(txt_age);
        txt_age.setBounds(180, 340, 170, 40);
        jPanel1.add(txt_contactNo);
        txt_contactNo.setBounds(560, 160, 170, 40);
        jPanel1.add(txt_department);
        txt_department.setBounds(560, 220, 170, 40);
        jPanel1.add(txt_doctor);
        txt_doctor.setBounds(560, 280, 170, 40);

        combo_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel1.add(combo_gender);
        combo_gender.setBounds(180, 280, 100, 40);

        button_register.setText("Register");
        button_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_registerActionPerformed(evt);
            }
        });
        jPanel1.add(button_register);
        button_register.setBounds(430, 440, 120, 60);

        button_clearForm.setText("Clear Form");
        button_clearForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_clearFormActionPerformed(evt);
            }
        });
        jPanel1.add(button_clearForm);
        button_clearForm.setBounds(240, 440, 120, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_registerActionPerformed
        // TODO add your handling code here:
       
        int x = JOptionPane.showConfirmDialog(null, "Confirm registration task ?", "Register Record", JOptionPane.YES_NO_OPTION);
        if (x == 0) {
            try {
                Calendar cal = new GregorianCalendar();
                int month = cal.get(Calendar.MONTH);
                int year = cal.get(Calendar.YEAR);
                int day = cal.get(Calendar.DAY_OF_MONTH);

                currentDate = day + ":" + month + ":" + year; 
                String sql = "insert into OutPatient "
                        + "(patientName, patientId, gender, age, contactNo, meetDate, "
                        + "department, doctor, admitDate) "
                        + "values (?, ?, ?, ?, ?, ?, ?, ?, ?)";
                pst = conn.prepareStatement(sql);
                pst.setString(1, txt_patientName.getText());
                pst.setString(2, txt_patientId.getText());
                pst.setString(3, combo_gender.getSelectedItem().toString());
                pst.setString(4, txt_age.getText());
                pst.setString(5, txt_contactNo.getText());
                pst.setString(6, txt_appointmentDate.getText());
                pst.setString(7, txt_department.getText());
                pst.setString(8, txt_doctor.getText());
                pst.setString(9, currentDate);

                pst.execute();
                JOptionPane.showMessageDialog(null, "Data is saved successfully");
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            finally {
                try {
    //                rs.close();
                    pst.close();
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }
    }//GEN-LAST:event_button_registerActionPerformed

    private void button_clearFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_clearFormActionPerformed
        // TODO add your handling code here:
        
        txt_age.setText("");
        txt_contactNo.setText("");
        txt_department.setText("");
        txt_doctor.setText("");
        txt_patientId.setText("");
        txt_patientName.setText("");
        txt_appointmentDate.setText("dd:mm:yyyy");
    }//GEN-LAST:event_button_clearFormActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OutPatientRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OutPatientRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OutPatientRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OutPatientRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OutPatientRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_clearForm;
    private javax.swing.JButton button_register;
    private javax.swing.JComboBox<String> combo_gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_appointmentDate;
    private javax.swing.JTextField txt_contactNo;
    private javax.swing.JTextField txt_department;
    private javax.swing.JTextField txt_doctor;
    private javax.swing.JTextField txt_patientId;
    private javax.swing.JTextField txt_patientName;
    // End of variables declaration//GEN-END:variables
    private String currentDate;
}
