/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system.Doctor;

import hospital.management.system.Database;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Sumanta
 */
public class DoctorInfo extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form DoctorInfo
     */
    public DoctorInfo() {
        initComponents();
        conn = Database.java_db();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        
        for (int col = 0; col < table_doctorInfo.getColumnCount(); col++) {
                table_doctorInfo.getColumnModel().getColumn(col).setPreferredWidth(200);
        }
        
        initiateComboBox();
    }

    private void initiateComboBox() {
        
        try {
            String sql = "Select distinct department from Doctor";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while (rs.next()) {
                combo_department.addItem(rs.getString("department"));
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Something happened with Combo");
        }
        finally {
            try {
                rs.close();
                pst.close();
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Something happened with Combo, oh God");
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        combo_department = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_doctorInfo = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        jPanel1.setLayout(null);

        jLabel2.setText("Enter Department");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 180, 110, 33);

        combo_department.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                combo_departmentMouseReleased(evt);
            }
        });
        jPanel1.add(combo_department);
        combo_department.setBounds(286, 180, 203, 33);

        table_doctorInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor Name", "Department", "Specializtion", "Contact No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_doctorInfo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        table_doctorInfo.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table_doctorInfo);
        if (table_doctorInfo.getColumnModel().getColumnCount() > 0) {
            table_doctorInfo.getColumnModel().getColumn(0).setResizable(false);
            table_doctorInfo.getColumnModel().getColumn(1).setResizable(false);
            table_doctorInfo.getColumnModel().getColumn(2).setResizable(false);
            table_doctorInfo.getColumnModel().getColumn(3).setResizable(false);
            table_doctorInfo.getColumnModel().getColumn(3).setPreferredWidth(33);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(65, 231, 691, 202);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(521, 180, 112, 33);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo_departmentMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combo_departmentMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_departmentMouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try {
            String sql = "Select name, department, specialization, contactNo"
                    + " from Doctor where department = ? ";
            
            pst = conn.prepareStatement(sql);
            pst.setString(1, combo_department.getSelectedItem().toString());
            rs = pst.executeQuery();
          
            ResultSetMetaData metaData = rs.getMetaData();
            
            Vector<String> columnNames = new Vector<String>();
            int columnCount  = metaData.getColumnCount();
            
            columnNames.add("Doctor Name");
            columnNames.add("Department");
            columnNames.add("Specialization");
            columnNames.add("Contact No");
            
            Vector<Vector<Object>> data = new Vector<Vector<Object>>();
            while (rs.next()) {
                
                Vector<Object> vector = new Vector<Object>();
                for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                    vector.add(rs.getObject(columnIndex));
                }
                data.add(vector);
            }
            DefaultTableModel tableModel = new DefaultTableModel(data, columnNames);
            table_doctorInfo.setModel(tableModel);
            
            for (int col = 0; col < table_doctorInfo.getColumnCount(); col++) {
                table_doctorInfo.getColumnModel().getColumn(col).setPreferredWidth(200);
            }
            
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Something happened");
        }
        finally {
            try {
                pst.close();
                rs.close();
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Something happened, oh God");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_department;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_doctorInfo;
    // End of variables declaration//GEN-END:variables
}
