/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system.Discharge;

import hospital.management.system.Database;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Sumanta
 */
public class DischargeInfo extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form DischargeInfo
     */
    public DischargeInfo() {
        initComponents();
        conn = Database.java_db();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_patientId = new javax.swing.JTextField();
        txt_patientName = new javax.swing.JTextField();
        txt_dischargeDate = new javax.swing.JTextField();
        txt_admitDate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setLayout(null);

        txt_patientId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_patientIdKeyTyped(evt);
            }
        });
        jPanel1.add(txt_patientId);
        txt_patientId.setBounds(370, 170, 203, 33);

        txt_patientName.setEditable(false);
        jPanel1.add(txt_patientName);
        txt_patientName.setBounds(370, 220, 203, 33);

        txt_dischargeDate.setEditable(false);
        jPanel1.add(txt_dischargeDate);
        txt_dischargeDate.setBounds(370, 320, 203, 33);

        txt_admitDate.setEditable(false);
        txt_admitDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_admitDateActionPerformed(evt);
            }
        });
        jPanel1.add(txt_admitDate);
        txt_admitDate.setBounds(370, 270, 203, 33);

        jLabel1.setText("Patient Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 220, 130, 33);

        jLabel2.setText("Enter Patient Id");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(210, 170, 130, 33);

        jLabel3.setText("Discharge Date");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(210, 320, 130, 33);

        jLabel4.setText("Admit Date");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(210, 270, 130, 33);

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete);
        btn_delete.setBounds(210, 400, 130, 43);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_admitDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_admitDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_admitDateActionPerformed

    private void txt_patientIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_patientIdKeyTyped
        // TODO add your handling code here:
        
        try {
            String sql = "Select * from DischargeSummary where patientId = ? ";
            
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_patientId.getText());
            rs = pst.executeQuery();
            
            String name = rs.getString("patientName");
            txt_patientName.setText(name);
            
            String admitDate = rs.getString("admitDate");
            txt_admitDate.setText(admitDate);
            
            String dischargeDate = rs.getString("dischargeDate");
            txt_dischargeDate.setText(dischargeDate);
            
        }
        catch (Exception e) {
            
        }
        finally {
            try {
                rs.close();
                pst.close();
            }
            catch (Exception e) {
                
            }
        }
    }//GEN-LAST:event_txt_patientIdKeyTyped

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        
        int x = JOptionPane.showConfirmDialog(null, "Confirm deletion task ?", "Delete Record", JOptionPane.YES_NO_OPTION);
        if (x == 0) {
            try {
                String sql = "delete from DischargeSummary where patientId = ? ";

                pst = conn.prepareStatement(sql);
                pst.setString(1, txt_patientId.getText());
                pst.execute();

                JOptionPane.showMessageDialog(null, "Record deleted");

                txt_admitDate.setText("");
                txt_dischargeDate.setText("");
                txt_patientId.setText("");
                txt_patientName.setText("");
            }
            catch (Exception e) {

            }
            finally {
                try {
                    pst.close();
                }
                catch (Exception e) {

                }
            }
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DischargeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DischargeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DischargeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DischargeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DischargeInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_admitDate;
    private javax.swing.JTextField txt_dischargeDate;
    private javax.swing.JTextField txt_patientId;
    private javax.swing.JTextField txt_patientName;
    // End of variables declaration//GEN-END:variables
}
